const FilterActionTypes = {
  SET_SIMPLE_ATTRIBUTTE: "SET_SIMPLE_ATTRIBUTTE",
  SET_ADDRESS_LOCATION: "SET_ADDRESS_LOCATION",
  SET_LOCATION_COORDINATES: "SET_LOCATION_COORDINATES",
  SET_COMPOUND_ATTRIBUTTE: "SET_COMPOUND_ATTRIBUTTE"
};

export default FilterActionTypes;
