const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_LANGUAGE: "SET_CURRENT_LANGUAGE",
  TOGGLE_LOGINDROPDOWN_HIDDEN: "TOGGLE_LOGINDROPDOWN_HIDDEN",
  TOGGLE_SHOW_PASSWORD: "TOGGLE_SHOW_PASSWORD"
};

export default UserActionTypes;
