const PropertyFormTypes = {
  SET_ADVERTISER_ATTRIBUTTE: "SET_ADVERTISER_ATTRIBUTTE",
  SET_FEATURE_ATTRIBUTTE: "SET_FEATURE_ATTRIBUTTE",
  SELECT_FEATURE_TYPE: "SELECT_FEATURE_TYPE",
  SET_LOCATION: "SET_LOCATION",
  SET_LOCATION_ATTRIBUTTE: "SET_LOCATION_ATTRIBUTTE",
  SET_LOCATION_BY_COORDINATE_PICKER: "SET_LOCATION_BY_COORDINATE_PICKER",  
  SET_IMAGES: "SET_IMAGES",
  SET_IMAGE_URL: "SET_IMAGE_URL",
  SET_FORM_STEP: "SET_FORM_STEP",
  SET_TOKEN: "SET_TOKEN",
  SET_EMPTY_FORM: "SET_EMPTY_FORM",
  SET_EDIT_PROPERTY: "SET_EDIT_PROPERTY",
  SAVE_PROPERTY_START: "SAVE_PROPERTY_START",
  SAVE_IMAGE_SUCCESS: "SAVE_IMAGE_SUCCESS",
  SAVE_PROPERTY_SUCCESS: "SAVE_PROPERTY_SUCCESS",
  SAVE_IMAGE_FAILURE: "SAVE_IMAGE_FAILURE",
  SAVE_PROPERTY_FAILURE: "SAVE_IMAGE_FAILURE"
};

export default PropertyFormTypes;
