const PropertyFormTypes = {
  SET_ADVERTISER_ATTRIBUTTE: "SET_ADVERTISER_ATTRIBUTTE",
  SET_FEATURE_ATTRIBUTTE: "SET_FEATURE_ATTRIBUTTE",
  SELECT_FEATURE_TYPE: "SELECT_FEATURE_TYPE",
  SET_LOCATION: "SET_LOCATION",
  SET_LOCATION_ATTRIBUTTE: "SET_LOCATION_ATTRIBUTTE",
  SET_LOCATION_BY_COORDINATE_PICKER: "SET_LOCATION_BY_COORDINATE_PICKER",  
  SET_FORM_STEP: "SET_FORM_STEP",
  SET_TOKEN: "SET_TOKEN"
};

export default PropertyFormTypes;
